apiVersion: v1
kind: ConfigMap
metadata:
  name: happi-api-config
  namespace: happimaintenance
data:
  DATABASE_NAME: "happimaintain"
  CORS_ORIGINS: "http://app.20.99.183.136.nip.io"
  ACCESS_TOKEN_EXPIRE_MINUTES: "15"
  REFRESH_TOKEN_EXPIRE_DAYS: "7"
